# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gaptool-server"
  s.version = "1.0.0"

  s.authors = ["Matt Bailey", "Francesco Laurita", "Giacomo Bagnoli"]
  s.date = "2014-06-27"
  s.description = "gaptool-server for managing cloud resources"
  s.email = "gbagnoli@gmail.com"
  s.executables = ["gaptool-server"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "Procfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/gaptool-server",
    "config.ru",
    "gaptool-server.gemspec",
    "lib/app.rb",
    "lib/helpers/gaptool-base.rb",
    "lib/helpers/init.rb",
    "lib/helpers/nicebytes.rb",
    "lib/helpers/partials.rb",
    "lib/helpers/rehash.rb",
    "lib/routes/init.rb",
    "lib/routes/main.rb",
    "lib/routes/rehash.rb",
    "lib/views/init.erb",
  ]
  s.homepage = "http://github.com/gild/gaptool-server"
  s.licenses = ["APACHE-2.0"]
  s.require_paths = ["lib"]
  s.summary = "gaptool-server for managing cloud resources"
end

